### ISSUE TITLE
Image not centered in KitKat Android version 4.4.2

### ISSUE THREAD

**Issue by erikswed** [cnlkl/TransformativeImageView#6]
Running on Marshmallow 6.01 the image is centered but same build on KitKat Android version 4.4.2 the image center point is right/bottom corner on the image, e.g. Any ide?

**Comment by erikswed** [comment]
my bad now it works ok

**Comment by cnlkl** [comment]
@erikswed , Bug has been repaired in the 1.1.3 version，try to update the version
``` gradle
dependencies {
	compile 'com.github.cnlkl:TransformativeImageView:1.1.3'
}
```

**Comment by erikswed** [comment]
Thanks will try it
